# Generated by Django 5.1.6 on 2025-03-10 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tache_assigne_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='assigne_a',
        ),
        migrations.AddField(
            model_name='tache',
            name='assigne_a',
            field=models.ManyToManyField(related_name='taches_assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
